services:
  - type: web
    name: backend-core-los-andes
    runtime: python
    region: ohio
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: FIREBASE_WEB_API_KEY
        sync: false
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "480"
      - key: CORS_ORIGINS
        value: https://frontend-portal-los-andes.vercel.app
      - key: ENV
        value: production
